#!/usr/bin/env bash
# Build the production MediaCodec pre-decode frame shedding
# (libavcodec/mediacodec_shed.c) for the host and run test_mediacodec_shed.c
# against it. Pass an already-patched ffmpeg tree for offline use; otherwise
# fetch and patch the pinned source in a temporary directory. The AV1 path
# needs FFmpeg's coded-bitstream reader, so a minimal host configure of the
# tree builds cbs and libavutil (no asm, no programs, ~20 s); no Android
# device or JNI runtime is needed.
#
# --regenerate rewrites test_mediacodec_shed_av1_sample.h from a fresh
# SVT-AV1 encode (needs a host ffmpeg with libsvtav1); the committed header is
# what the test normally runs against.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_dir=""
regenerate=0
for arg in "$@"; do
    case "$arg" in
        --regenerate) regenerate=1 ;;
        *) source_dir="$arg" ;;
    esac
done
workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

if [[ $regenerate -eq 1 ]]; then
    ffmpeg -hide_banner -loglevel error -y -f lavfi -i "testsrc2=size=64x64:rate=24:duration=1" \
        -pix_fmt yuv420p -c:v libsvtav1 -preset 12 -crf 40 -g 100 \
        -svtav1-params "lp=1:pred-struct=2:hierarchical-levels=3" -f obu "$workdir/sample.obu"
    python3 - "$workdir/sample.obu" "$root/scripts/test_mediacodec_shed_av1_sample.h" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
lines = ['    ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',' for i in range(0, len(data), 16)]
open(sys.argv[2], 'w').write(
    '// A 64x64, 24-frame SVT-AV1 random-access stream (Section 5 OBU stream,\n'
    '// one temporal unit per shown frame, hidden alt-refs and show_existing_frame\n'
    '// units included). Generated by test_mediacodec_shed.sh --regenerate.\n'
    'static const uint8_t av1_sample[] = {\n' + '\n'.join(lines) + '\n};\n')
PY
    echo "regenerated $(wc -c < "$workdir/sample.obu") bytes of AV1"
fi

if [[ -z "$source_dir" ]]; then
    source_dir="$workdir/source"
    # The pin contract lives in scripts/patches.py: it resolves the
    # override-aware pin, clones the ref, proves HEAD is the pinned commit
    # and applies the resolved ffmpeg/android series.
    (cd "$root" && python3 scripts/patches.py fetch-pinned ffmpeg android "$source_dir")
fi
source_dir="$(cd "$source_dir" && pwd)"

# A host build of just what the reader needs. The mediacodec decoders are
# off in this configuration; the shim below turns the AV1 section of the
# shed module back on so the test covers it.
build="$workdir/build"
mkdir -p "$build"
(cd "$build" && "$source_dir/configure" --disable-everything --disable-programs --disable-doc \
    --disable-network --disable-autodetect --disable-asm --enable-decoder=av1 >"$workdir/configure.log" 2>&1) \
    || { cat "$workdir/configure.log"; exit 1; }
make -C "$build" -j"$(getconf _NPROCESSORS_ONLN)" libavutil/libavutil.a libavcodec/cbs.o \
    libavcodec/cbs_av1.o libavcodec/packet.o >"$workdir/make.log" 2>&1 || { tail -50 "$workdir/make.log"; exit 1; }

cat >"$workdir/shed_shim.c" <<'C'
#include "config.h"
#include "config_components.h"
#undef CONFIG_AV1_MEDIACODEC_DECODER
#define CONFIG_AV1_MEDIACODEC_DECODER 1
#include "libavcodec/mediacodec_shed.c"
C

cflags=(-O2 -std=c17 -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
        -DHAVE_AV_CONFIG_H -D_ISOC11_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
        -I"$build" -I"$source_dir" -I"$root/scripts")
cc "${cflags[@]}" -Werror -c -o "$workdir/shed.o" "$workdir/shed_shim.c"
cc "${cflags[@]}" -Werror -c -o "$workdir/test.o" "$root/scripts/test_mediacodec_shed.c"
cc -o "$workdir/test" "$workdir/test.o" "$workdir/shed.o" "$build/libavcodec/cbs.o" \
    "$build/libavcodec/cbs_av1.o" "$build/libavcodec/packet.o" "$build/libavutil/libavutil.a" -lm -lpthread
"$workdir/test"
